server:
   port: 8080
customer.service.getcust: http://customer-service/get/
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
     
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
    
#H2 Database UI Enable      
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#RabbitMQ Properties
spring:
   rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
            
#spring.main.allow-bean-definition-overriding: true
#javainuse.rabbitmq.exchange=javaTechM.exchange
#javainuse.rabbitmq.queue=javaTechM.queue
#javainuse.rabbitmq.routingkey=javaTechM.routingkey
