--- 
eureka: 
  client: 
    healthcheck: 
      enabled: true
    lease: 
      duration: 5
    serviceUrl: 
      defaultZone: "http://localhost:8761/eureka/"
  instance: 
    leaseExpirationDurationInSeconds: 2
    leaseRenewalIntervalInSeconds: 1
info: 
  app: 
    description: "This is my first spring boot application"
    name: "Spring Sample Application"
    version: "1.0.0"
management: 
  endpoints: 
    web: 
      exposure: "include:*"
server: 
  port: 8089
spring: 
  application: 
    name: item-service
