server:
    port: 8181
itemservices:
    chkname: http://item-service/get?name=
#customer:
#    service:
#      getcust: http://customer-service/customer-services/get/
customer.service.getcust: http://customer-service/get/
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

#for Ribbon Load Balancing
server:
    ribbon:
        eureka:
            enabled: true
        ServerListRefreshInterval: 1000
        
#for RabitMQ 
spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
spring:
    cloud:
        stream:
            bindings:
                input:
                    destination: customerRegistrations
                    group: customerRegistrationQueue
