server:
    port: 8181
itemservices:
    chkname: http://item-service/item-services/get?name=
customer:
    service:
      getcust: http://customerservice/customer-services/get/
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:
  application:
    name: sales-order-service    #service name